name: liquid_ball
description: An animated waterdrop ball component that can use gradients, margins, and animation controllers.
version: 1.0.3
# repository: https://github.com/my_org/my_repo
license: MIT 
homepage: https://github.com/Azad-Zhang/flutter_liquid_ball
repository: https://github.com/Azad-Zhang/flutter_liquid_ball

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=2.19.0"     # Flutter SDK 最低版本

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0



dev_dependencies:
  # lints: ^3.0.0
  # test: ^1.24.0
  flutter_test:
    sdk: flutter  # 测试依赖（可选但推荐）
  # flutter_lints: ^2.0.0  # 代码规范检查（推荐）
